### ISSUE TITLE
Suppression d'une ligne de frais

### ISSUE THREAD

**Issue by jframiara** [m2l-limayrac/Fredy#11]
Quand on veut supprimer la ligne 8 de corentin.diolo, on obtient une erreur : "Objet non trouvé. L'URL demandée n'a pas pu être trouvée sur ce serveur."
L'URL recherchée est : http://localhost/Fredy/web/demandeur/drop_line/8
L'application est installée sur "http://localhost/projets/PPE3/plot3/web/"

**Comment by AlexisLapeze** [comment]
Dans le README.md : 
> Créé un dossier nommé 'Fredy' dans le dossier eds-www de easyPHP et déplacer le fichier cloner à l'intérieur

Le problème doit venir du fait qu'il ne faut pas que le projet soit dans une dossier "plot3"

**Comment by AlexisLapeze** [comment]
le lien étais bien écrit en dur dans le code.
Résolu ici : #18
