### ISSUE TITLE
Clubs en double dans le PDF

### ISSUE THREAD

**Issue by jframiara** [m2l-limayrac/Fredy#5]
Dans le PDF de Simon Berbier, on peu lire que le remboursement des frais est à deux clubs, ce qui est fiscalement impossible. Deux clubs ne peuvent pas déclarer les mêmes frais.
Il manquerait aussi éventuellement les couleurs dans le PDF (voir exemple du sujet).

**Comment by JulienPinet** [comment]
fix ici #17
