### ISSUE TITLE
2x le nom lors de l'inscription

### ISSUE THREAD

**Issue by jframiara** [m2l-limayrac/Fredy#7]
Quand on veut s'inscrire, plusieurs infos sont demandées deux fois (nom, prénom, rue...). Ce n'est pas compréhensible.

**Comment by RousselC** [comment]
Si c'est pour la création d'un représentant c'est normal car la première phase du formulaire concerne le représentant (nom, prénom, adresse, ...) et une fois qu'on valide ce formulaire on arrive sur une autre page de formulaire ou la, on a de nouveau des champs (nom, prénom, adresse, ...) mais qui concerne l’adhérent mineur car ces champs peuvent être différant par rapport au représentant.
Apres pour l'adhérant simple je ne vois pas un problème de doublon de champ lors de l’inscription.

**Comment by AlexisLapeze** [comment]
Même chose que ici #9. Il faut privilégier chrome. Le site est très mal supporter sur Firefox.
