### ISSUE TITLE
Inscription impossible

### ISSUE THREAD

**Issue by jframiara** [m2l-limayrac/Fredy#9]
Le bouton "VALIDER" reste grisé quand on essaye de s'inscrire même si on remplit tous les champs.

**Comment by RousselC** [comment]
J'ai testé toutes les inscriptions, lorsque l'on emplie tous les champs, le bouton "VALIDER" passer bien au bleu.

**Comment by AlexisLapeze** [comment]
Il faut privilégier chrome. Le site est très mal supporter sur Firefox.
